all:creater sender receiver
creater:creater.c 1.h
	gcc creater.c 1.h -o creater
sender:sender.c 1.h
	gcc sender.c 1.h -o sender
receiver:receiver.c 1.h
	gcc receiver.c 1.h -o receiver

clean:
	rm -rf creater sender receiver
